apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appa-a
  template:
    metadata:
      labels:
        app: appa-a
    spec:
      containers:
        - image: kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          name: appa-a
          ports:
            - containerPort: 80
