apiVersion: v1
kind: Service
metadata:
  name: httpbin1
  labels:
    app: httpbin1
    service: httpbin1
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpbin1
