{{- range $index, $app := .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: '{{ default 0 $app.syncWave }}'
spec:
  destination:
    namespace: {{ default $namespace $app.namespace }}
    server: https://kubernetes.default.svc
  project: my-project
  source:
    path: {{ $app.path }}
    repoURL: {{ $.Values.gitops.repo }}
    targetRevision: {{ $.Values.gitops.revision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
