# argo app defaults
argoApp:
  prefix: myapps-clustera-dev-
  namespace: argocd

# default for applications
app:
  repo: https://github.com/merikan/gitops
  revision: main
  namespace: myapps-dev
  partOf: myapps
  prune: false
  selfHeal: true

# List of argocd applications
#   Available options:
#   - name : name (mandatory)
#   - path : absolute path to manifest(s) (mandatory)
#   - namespace : destination namespace (optional)
#   - syncWave : if syncwave is to be used, default=0 (optional)
#   - prune : should automatic pruning be active, true/false (optional)
#   - selfHeal: should automatoc selfhealing be active, true/false (optional)
apps:
  - name: app-a
    path: apps/app-a/k8s/envs/dev
  # - name: app-b
  #   path: apps/app-b/envs/dev
  # - name: app-c
  #   path: apps/app-c/envs/dev
  #   namespace: myapps-dev2
  #   syncWave: 3
  #   prune: true
  #   selfHeal: true
