apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
        - image: kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          name: app-b
          ports:
            - containerPort: 80
